name: Deploy Fullstack App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # your local/self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy app
        working-directory: /home/runner/fullstack-app
        run: |
          echo "Pulling latest Docker image..."
          docker pull abdo02/fullstack-app:latest

          echo "Stopping old containers..."
          docker compose down --remove-orphans

          echo "Starting new containers..."
          docker compose up -d --force-recreate

          echo "Cleaning up old images..."
          docker image prune -f
